---

apiVersion: v1
kind: ConfigMap
metadata:
  name: csi-config
data:
  Url: "http://10.17.3.1:8050"


---

apiVersion: v1
kind: Secret
metadata:
  name: secret-csi-config
type: Opaque
data:
  Username: YmFyCg==
  Password: YmFyCg==

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-csi-luks
type: Opaque
data:
  password: YmFyCg==

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-plugin
spec:
  selector:
    matchLabels:
      name: node-plugin
  template:
    metadata:
      labels:
        name: node-plugin
    spec:
      volumes:
        - name: secret-csi-luks
          secret:
            secretName: secret-csi-luks
        - name: csi-config
          configMap:
            name: csi-config
        - name: mnt
          hostPath:
            path: /mnt
        - name: device-dir
          hostPath:
            path: /dev
        - name: id
          hostPath:
            path: /etc/hostname
        - name: pods-vol-dir
          hostPath:
            path: /var/lib/kubelet
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/Libvirtapi/
            type: DirectoryOrCreate
      containers:
      - name: csi-driver-registrar
        securityContext:
          privileged: true
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.1
        args:
          - "--csi-address=/csi/csi.sock"
          - "--kubelet-registration-path=/var/lib/kubelet/plugins/Libvirtapi/csi.sock"
          - "-v=5"
        volumeMounts:
          - name: csi-config
            mountPath: /etc/csi/conf.json
          - name: plugin-dir
            mountPath: /csi
          - name: registration-dir
            mountPath: /registration
          - name: mnt
            mountPath: /mnt
            mountPropagation: "Bidirectional"
          - name: pods-vol-dir
            mountPath: /var/lib/kubelet
            mountPropagation: "Bidirectional"
          - name: device-dir
            mountPath: /dev
      - name: node-plugin
        image: repo.mgmt.autok8s.ext:5000/csi-libvirt:latest
        args:
          - "--endpoint=$(CSI_ENDPOINT)"
          - "--role=node"
          - "--url=$(CSI_URL_API)"
          - "--user=$(USER_API)"
          - "--pass=$(PASS_API)"
        env:
          - name: "CSI_ENDPOINT"
            value: "unix:///csi/csi.sock"
          - name: "CSI_URL_API"
            valueFrom:
              configMapKeyRef:
                name: csi-config
                key: Url
          - name: USER_API
            valueFrom:
              secretKeyRef:
                name: secret-csi-config
                key: Username
          - name: PASS_API
            valueFrom:
              secretKeyRef:
                name: secret-csi-config
                key: Password
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: "/etc/luks"
            name: secret-csi-luks
            readOnly: true          
          - name: csi-config
            mountPath: /etc/csi
          - name : id
            mountPath: /id
          - name: pods-vol-dir
            mountPath: /var/lib/kubelet
            mountPropagation: "Bidirectional"
          - name: mnt
            mountPath: /mnt
            mountPropagation: "Bidirectional"
          - name: device-dir
            mountPath: /dev
          - name: plugin-dir
            mountPath: /csi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-libvirt-deployment
  labels:
    app: csi-libvirt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-libvirt
  template:
    metadata:
      labels:
        app: csi-libvirt
    spec:
      serviceAccountName: csi-libvirt-sa
      containers:
        - name: external-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.6.0
          args:
            - "--csi-address=$(CSI_ENDPOINT)"
            - "-v=5"
          env:
            - name: "CSI_ENDPOINT"
              value: "unix:///sock/csi.sock"
          volumeMounts:
            - mountPath: /sock
              name: sock-volume

        - name: external-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.0.0
          args:
            - "--csi-address=$(CSI_ENDPOINT)"
          env:
            - name: "CSI_ENDPOINT"
              value: "unix:///sock/csi.sock"
          volumeMounts:
            - mountPath: /sock
              name: sock-volume

        - name: csi-libvirt
          image: repo.mgmt.autok8s.ext:5000/csi-libvirt:latest
          args: 
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--role=controler"
            - "--url=$(CSI_URL_API)"
            - "--user=$(USER_API)"
            - "--pass=$(PASS_API)"
          env:
            - name: "CSI_ENDPOINT"
              value: "unix:///sock/csi.sock"
            - name: "CSI_URL_API"
              valueFrom:
                configMapKeyRef:
                  name: csi-config
                  key: Url
            - name: USER_API
              valueFrom:
                secretKeyRef:
                  name: secret-csi-config
                  key: Username
            - name: PASS_API
              valueFrom:
                secretKeyRef:
                  name: secret-csi-config
                  key: Password
          volumeMounts:          
            - name : id
              mountPath: /id
            - name: csi-config
              mountPath: /etc/csi
            - mountPath: /sock
              name: sock-volume

      volumes:
        - name: id
          hostPath:
            path: /etc/hostname
        - name: csi-config
          configMap:
            name: csi-config
        - name: sock-volume
          emptyDir: {}