apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-plugin
spec:
  selector:
    matchLabels:
      name: node-plugin
  template:
    metadata:
      labels:
        name: node-plugin
    spec:
      volumes:
        - name: mnt
          hostPath:
            path: /mnt
        - name: device-dir
          hostPath:
            path: /dev
        - name: id
          hostPath:
            path: /etc/hostname
        - name: pods-vol-dir
          hostPath:
            path: /var/lib/kubelet
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/Libvirtapi/
            type: DirectoryOrCreate
      containers:
      - name: csi-driver-registrar
        securityContext:
          privileged: true
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.0
        args:
          - "--csi-address=/csi/csi.sock"
          - "--kubelet-registration-path=/var/lib/kubelet/plugins/Libvirtapi/csi.sock"
          - "-v=5"
        volumeMounts:
          - name: plugin-dir
            mountPath: /csi
          - name: registration-dir
            mountPath: /registration
          - name: mnt
            mountPath: /mnt
            mountPropagation: "Bidirectional"
          - name: pods-vol-dir
            mountPath: /var/lib/kubelet
            mountPropagation: "Bidirectional"
          - name: device-dir
            mountPath: /dev
      - name: node-plugin
        image: repo.mgmt.autok8s.ext:5000/csi-libvirt:latest
        args:
          - "--endpoint=$(CSI_ENDPOINT)"
          - "--role=node"
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        securityContext:
          privileged: true
        volumeMounts:
          - name : id
            mountPath: /id
          - name: pods-vol-dir
            mountPath: /var/lib/kubelet
            mountPropagation: "Bidirectional"
          - name: mnt
            mountPath: /mnt
            mountPropagation: "Bidirectional"
          - name: device-dir
            mountPath: /dev
          - name: plugin-dir
            mountPath: /csi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-libvirt-deployment
  labels:
    app: csi-libvirt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-libvirt
  template:
    metadata:
      labels:
        app: csi-libvirt
    spec:
      serviceAccountName: csi-libvirt-sa
      containers:
        - name: external-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.6.0
          args:
            - "--csi-address=$(CSI_ENDPOINT)"
            - "-v=5"
          env:
            - name: "CSI_ENDPOINT"
              value: "unix:///sock/csi.sock"
          volumeMounts:
            - mountPath: /sock
              name: sock-volume

        - name: external-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.0.0
          args:
            - "--csi-address=$(CSI_ENDPOINT)"
          env:
            - name: "CSI_ENDPOINT"
              value: "unix:///sock/csi.sock"
          volumeMounts:
            - mountPath: /sock
              name: sock-volume

        - name: csi-libvirt
          image: repo.mgmt.autok8s.ext:5000/csi-libvirt:latest
          args: 
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--role=controler"
          env:
            - name: "CSI_ENDPOINT"
              value: "unix:///sock/csi.sock"
          volumeMounts:
            - mountPath: /sock
              name: sock-volume

      volumes:
      - name: sock-volume
        emptyDir: {}