apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lva
provisioner: Libvirtapi
volumeBindingMode: Immediate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-lva 
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: lva 