---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lva-encrypt
provisioner: Libvirtapi
volumeBindingMode: Immediate

allowVolumeExpansion: true
mountOptions:
  - "-v"
parameters:
  url: "true" # provider-specific
  readOnly: "false"
  diskformat: "true"
  encrypt: "true"
  tang_server: tang.autok8s.xyz
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-lva-encrypt
  annotations:
    storageclass.kubernetes.io/is-encrypt: "true"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: lva-encrypt 

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lva
provisioner: Libvirtapi
volumeBindingMode: Immediate

allowVolumeExpansion: true
mountOptions:
  - "-v"
parameters:
  url: "true" # provider-specific
  readOnly: "false"
  diskformat: "true"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-lva 
  annotations:
    storageclass.kubernetes.io/is-encrypt: "true"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: lva
